### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [mukulsharma97/Heliware_Plugin#1]
Please remove unnecessary files which are generated on the install __pycache etc

**Comment by NyakudyaA** [comment]
ping @mukulsharma97

**Comment by mukulsharma97** [comment]
@NyakudyaA 
i removed unnecessary file from plugin zip file. Please suggest next step to get approval of my QGIS Plugin.

**Comment by NyakudyaA** [comment]
approved

**Comment by mukulsharma97** [comment]
@NyakudyaA 
Thank You.

**Comment by NyakudyaA** [comment]
Please also remove the _pycache folder from the repo just in case people need to install using the zip rather than the official plugin

**Comment by mukulsharma97** [comment]
@NyakudyaA 
I used one external python module "haversine" in my plugin, i also define this python module in metadata as shown in image
![image](https://user-images.githubusercontent.com/64946831/137899009-2827ea79-ae9d-4ebb-a6f1-ff5248ab27b5.png)

 but at a time of plugin installing QGIS does not install python module in QGIS python environment. Please suggest how to resolve this issue, so at a time of plugin installation extra python module will be automatically install in QGIS python environment.

**Comment by mukulsharma97** [comment]
@NyakudyaA 
when i install my plugin from QGIS then i facing below error:
![image](https://user-images.githubusercontent.com/64946831/137911626-66bcfa6c-4e18-4de4-bc4e-659a5d4ebb1a.png)


Please suggest how to define extra python module in QGIS plugin, so at a time of plugin installation extra python module will be automatically install in QGIS python environment.

**Comment by mukulsharma97** [comment]
@NyakudyaA 
Please suggest me how to resolve above issue ASAP.

**Comment by NyakudyaA** [comment]
> @NyakudyaA Please suggest me how to resolve above issue ASAP.

Please write to qgis-developer@lists.osgeo.org asking for help or any gis stake exchange. I help out with the plugin approval pro bono. I will take a look when I have a free moment

**Comment by mukulsharma97** [comment]
@NyakudyaA ,

I resolved above issue in my plugin and again publish it for QGIS, Please review and provide approval of my plugin.

**Comment by mukulsharma97** [comment]
@NyakudyaA 

Please review my updated QGIS Plugin and provide approval ASAP. I am waiting of your response.
